### ISSUE TITLE
[LinuxDays2017] make error

### ISSUE THREAD

**Issue by alan717** [tantecky/mystuff#1]
i download your project and read your pdf tutorial .but i got this ,could you help me ?
```
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld -s -z noexecstack -o runme runme.o
python3 ./prepare.py
Warning: Cannot initialize dynamic strings
Traceback (most recent call last):
  File "./prepare.py", line 8, in <module>
    text_section = sections['LOAD1']
KeyError: 'LOAD1'
make: *** [Makefile:10：runme] 错误 1
```    
my environment :  
1.  ` Linux version 4.14.57-1-MANJARO (builduser@development) (gcc version 8.1.1 20180531 (GCC)) #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 201`  
2.  pip install r2pipe   
3.  r2dare   
thanks a lot

**Comment by tantecky** [comment]
Apparently there had been some changes in radare2 API, so I've updated the script prepare.py (82efcefe8ebc1e6299d5e484aa589cace40008f3) Give it a new try and let me know. Thank you.
