### ISSUE TITLE
[LinuxDays2017] Prepare.py Error

### ISSUE THREAD

**Issue by ddrexler** [tantecky/mystuff#2]
Hi!

after the make command I get the following error:

`root@kali:~/mystuff/LinuxDays2017# make
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld -s -z noexecstack -o runme runme.o
python3 ./prepare.py
Warning: Cannot initialize dynamic strings
Text section end: 0x40230d
Traceback (most recent call last):
  File "./prepare.py", line 19, in <module>
    key = str(hex(r2.cmdj('pdj 1 @ ' + enc)[0]['ptr']))
KeyError: 'ptr'
Makefile:9: recipe for target 'runme' failed
make: * [runme] Error 1`

I installed the r2pipe module with
pip3 install r2pipe

Thanks for your help and the repo & presentation.

**Comment by tantecky** [comment]
Hi,
That is really a weird error. Could you provide me more information about your setup? By running the following commands:
```
uname -a
r2 --version
nasm -v
```
Finally after receiving the error run the command: `r2 -qc '/c inc rcx; pd 3 @ hit0_0' runme` and paste the obtained output here.
Thx

**Comment by ddrexler** [comment]
Output of the commands:
```
root@kali: uname -r
4.12.0-kali1-amd64
root@kali:~# r2 --version
r2: invalid option -- '-'
radare2 1.6.0 0 @ linux-x86-64 git.1.6.0
commit: HEAD build: 2017-07-12__00:23:24
root@kali:~# nasm -v
NASM version 2.13.01
```

After failed make:

```
r2 -qc '/c inc rcx; pd 3 @ hit0_0' runme
root@kali:~/mystuff/LinuxDays2017# r2 -qc '/c inc rcx; pd 3 @ hit0_0' runme
Warning: Cannot initialize dynamic strings
0x00401077   # 3: inc rcx
0x004010bf   # 3: inc rcx
0x00402077   # 3: inc rcx
0x004020bf   # 3: inc rcx
0x00402107   # 3: inc rcx
0x0040214f   # 3: inc rcx
0x00402197   # 3: inc rcx
0x004021df   # 3: inc rcx
0x00402227   # 3: inc rcx
0x0040226f   # 3: inc rcx
0x004022b7   # 3: inc rcx
            ;-- hit0_0:
            0x00401077      ff             invalid
            0x00401078      ff             invalid
            0x00401079      ff             invalid
```

**Comment by tantecky** [comment]
Your version of radare2 is pretty old. Can you use one from github. Than run `r2 --version` again to confirm.
