### ISSUE TITLE
[LinuxDays2017] make error , ld: warning: option -s is obsolete and being ignored

### ISSUE THREAD

**Issue by hit-monchan** [tantecky/mystuff#3]
I am having an issue when i run make

```
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld -s -z noexecstack -o runme runme.o
ld: warning: option -s is obsolete and being ignored
ld: unknown option: -z
make: *** [runme] Error 1
```

My environment : 

1. Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

2. NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Nov  6 2017

Appreciate for help please. Thank you in advance.

**Comment by tantecky** [comment]
The example is designed/tested for Linux. I have never tried it on mac. The issue seems to be that Apple's linker does not support some options. I have modified the makefile so you can try to use linker from LLVM project (`brew install llvm`) and then run `git pull && make`.

**Comment by hit-monchan** [comment]
Thanks for the quick response.

I tried to use linker from LLVM and also run `git pull && make` on mac. There are some errors observed.

```
# make
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld64.lld -s -z noexecstack -o runme runme.o
ld64.lld: warning: ignoring unknown argument: -s
ld64.lld: warning: ignoring unknown argument: -z
ld64.lld: error: -arch not specified and could not be inferred
make: *** [runme] Error 1
```
I encountered this error "`ld64.lld: error: -arch not specified and could not be inferred`" and modified the command below to specify -arch and then run `make`.

`$(LD) -s -z noexecstack -o $(BIN_FILE) $(OBJ_FILES) -arch x86_64`

```
# make
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld64.lld -s -z noexecstack -o runme runme.o -arch x86_64
ld64.lld: warning: ignoring unknown argument: -s
ld64.lld: warning: ignoring unknown argument: -z
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
Cannot open noexecstack: No such file or directory
make: *** [runme] Error 1
```

And encountered this error "`Cannot open noexecstack: No such file or directory`" and modified the command below then run `make`.

`$(LD) -o $(BIN_FILE) $(OBJ_FILES) -arch x86_64`

```
# make
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld64.lld -o runme runme.o -arch x86_64
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
Cannot open runme.o: Exec format error
make: *** [runme] Error 1
```

And encountered this error "`Cannot open runme.o: Exec format error`" and so I modified the command below then run `make`.

`$(AS) -f macho64 -o $@ $<`

```
# make
rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f macho64 -o runme.o runme.asm
runme.asm:23: error: unknown section name

runme.asm:23: error: segment name `.mytext' not recognized
make: *** [runme.o] Error 1

```

And encountered this error "`runme.asm:23: error: unknown section name`" 

Appreciate for help please. Thank you in advance.

**Comment by tantecky** [comment]
A realible way how to run the example is by installing Linux into VirtualBox on your machine.

**Comment by hit-monchan** [comment]
I have tested on Linux as well. It was working fine. Thanks for the help.
