### ISSUE TITLE
[LinuxDays2017] Make Error

### ISSUE THREAD

**Issue by ilikecheese8888** [tantecky/mystuff#4]
Running make with Python 3.6 it claims that there is an error in the code for prepare.py

rm -f runme.o
rm -f runme
rm -f *.bak
nasm -f elf64 -o runme.o runme.asm
ld -s -z noexecstack -o runme runme.o
python3 ./prepare.py
Text section end: 0x6003fd
r2pipe.cmdj.Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./prepare.py", line 13, in <module>
    enc_starts = [hit['offset'] for hit in hits]
TypeError: 'NoneType' object is not iterable
make: *** [runme] Error 1

**Comment by tantecky** [comment]
Hi, radare2 is a moving beast, so the example stops working from time to time. I have made a new commit to fix it for the current version (i.e. 3.8.0). Give it a shot.
